### PR TITLE
PR for Add labels for atlas oparator

### LINKED ISSUE #160: Atlas operator chart custom labels
Hello! We currently integrate atlas operator to our infrastructure, but we find out lack of labels customisation for sake of inventory/security etc inside infra. I will create PR for atlas chart for custom labels ( as well for CRD ) If this functionality could be merged in upstream it will be cool so we don't need to download chart and customize it for us.

### PR DESCRIPTION
**Pull request by qtranton**
Issue https://github.com/mongodb/helm-charts/issues/160
### All Submissions:

* [x] Have you opened an Issue before filing this PR?
* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Put `closes #160` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Review by helderjs — APPROVED** [review]
LGTM

**Comment by helderjs** [comment]
it needs rebase

**Comment by Sugar-pack** [comment]
@helderjs, @fabritsius. I think this PR should be closed. Because labels covered by this commit: https://github.com/mongodb/helm-charts/commit/5f59c47ca636c5b700fe7ba07e43304553ef9c0c

**Comment by helderjs** [comment]
> @helderjs, @fabritsius. I think this PR should be closed. Because labels covered by this commit: [5f59c47](https://github.com/mongodb/helm-charts/commit/5f59c47ca636c5b700fe7ba07e43304553ef9c0c)

you're right! it's actually the same. we should close it.

**Comment by helderjs** [comment]
done in https://github.com/mongodb/helm-charts/pull/178

**Pull request closed without merging**
