### PR TITLE
Allow setting custom labels on mongo operator pod

### PR DESCRIPTION
**Pull request by aistoica**
### All Submissions:

* [x] Have you opened an Issue before filing this PR?
* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by aistoica** [comment]
closes #345

**Review by s-urbaniak — APPROVED** [review]

**Comment by s-urbaniak** [comment]
generally LGTM but setting up a proof PR against the AKO repository to verify that e2e succeeds.

**Review by josvazg — APPROVED** [review]
Change LGTM, thanks for the contribution!

**Review by igor-karpukhin — APPROVED** [review]

**Comment by s-urbaniak** [comment]
LGTM once https://github.com/mongodb/mongodb-atlas-kubernetes/pull/1786 is green. Thank you for the contribution!

**Comment by s-urbaniak** [comment]
This changed passed all e2e tests on the proof PR, merging 🎉

**Pull request merged**
